# Generated by Django 5.1.7 on 2025-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clubhead_deanofstudentaffairs_facultyincharge_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubhead',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='deanofstudentaffairs',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='facultyincharge',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='iqac',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='resourceapprovalperson',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255, unique=True),
        ),
    ]
