# Generated by Django 5.1.7 on 2025-03-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clubhead_email_deanofstudentaffairs_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.TextField()),
                ('podium', models.IntegerField(default=0)),
                ('mic', models.IntegerField(default=0)),
                ('led', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('participants', models.IntegerField()),
                ('suggested_hall', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
